#redis配置
spring:
  redis:
  #    服务器地址
    host: 192.168.1.12
  #    服务器连接端口
    port: 6379
  #    链接密码
    password: zjtachao
  #    链接池
    pool:
  #    最大连接数（负值表示没有限制）
      max-active: 20
  #      最大阻塞等待时间（负值表示没有限制）
      max-wait: 1000
  #      最大空闲链接
      max-idle: 10
  #      最小空闲链接
      min-idle: 0
  #    链接超时时间（毫秒）
    timeout: 0